site_name: Pyright for PyCharm
site_description: A PyCharm plugin that runs Pyright as you code
site_url: https://insyncwithfoo.github.io/pyright-for-pycharm

repo_name: InSyncWithFoo/pyright-for-pycharm
repo_url: https://github.com/InSyncWithFoo/pyright-for-pycharm

edit_uri: blob/master/docs/

exclude_docs: |
  /requirements.txt

theme:
  name: material
  favicon: assets/icon.svg
  logo: assets/icon-outline.svg
  palette:
    -
      media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: octicons/sun-16
        name: "Switch to dark mode"
    -
      media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: octicons/moon-16
        name: "Switch to light mode"
  features:
    - content.action.edit
    - content.action.view
    - navigation.indexes
    - search.suggest

markdown_extensions:
  admonition:
  codehilite:
  md_in_html:
  pymdownx.details:
  pymdownx.tabbed:
    alternate_style: true
    combine_header_slug: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
  pymdownx.smartsymbols:
    arrows: true
    care_of: false
    copyright: false
    fractions: false
    notequal: false
    ordinal_numbers: false
    plusminus: false
    registered: false
    trademark: false
  pymdownx.superfences:
  toc:
    permalink: '#'

nav:
  - Overview: index.md
  - Configurations:
    - Overview: configurations/index.md
    - Running modes: configurations/running-modes.md
    - Executables: configurations/executables.md
    - Inspection: configurations/inspection.md
    - Other: configurations/other.md
  - IDE actions: actions.md
  - Other features: features.md
  - Problems: problems.md
  - Logging: logging.md
  - How-to guides: how-to.md
  - FAQ: faq.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

strict: true
