[versions]
# libraries
annotations = "24.1.0"
kotlinxSerialization = "1.6.3"

# plugins
kotlin = "1.9.22"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.2"
qodana = "0.1.13"
kover = "0.7.6"

[libraries.annotations]
group = "org.jetbrains"
name = "annotations"
version.ref = "annotations"

[libraries.kotlinxSerialization]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-json"
version.ref = "kotlinxSerialization"

[plugins.changelog]
id = "org.jetbrains.changelog"
version.ref = "changelog"

[plugins.gradleIntelliJPlugin]
id = "org.jetbrains.intellij"
version.ref = "gradleIntelliJPlugin"

[plugins.kotlin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.kover]
id = "org.jetbrains.kotlinx.kover"
version.ref = "kover"

[plugins.qodana]
id = "org.jetbrains.qodana"
version.ref = "qodana"

[plugins.kotlinSerialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin"
