[versions]
# libraries
annotations = "26.0.2-1"
kotlinxSerialization = "1.9.0"
junit = "4.13.2"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.8.0"
kotlin = "2.2.10"
kover = "0.9.1"
qodana = "2025.2.1"

[libraries.annotations]
group = "org.jetbrains"
name = "annotations"
version.ref = "annotations"

[libraries.kotlinxSerialization]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-json"
version.ref = "kotlinxSerialization"

[libraries.junit]
group = "junit"
name = "junit"
version.ref = "junit"

[plugins.changelog]
id = "org.jetbrains.changelog"
version.ref = "changelog"

[plugins.intelliJPlatform]
id = "org.jetbrains.intellij.platform"
version.ref = "intelliJPlatform"

[plugins.kotlin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.kover]
id = "org.jetbrains.kotlinx.kover"
version.ref = "kover"

[plugins.qodana]
id = "org.jetbrains.qodana"
version.ref = "qodana"

[plugins.kotlinSerialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin"
