[versions]
# libraries
annotations = "24.1.0"
kotlinxSerialization = "1.7.1"

# plugins
changelog = "2.2.1"
intellijPlatform = "2.0.0-beta9"
kotlin = "2.0.0"
kover = "0.8.2"
qodana = "2024.1.5"

[libraries.annotations]
group = "org.jetbrains"
name = "annotations"
version.ref = "annotations"

[libraries.kotlinxSerialization]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-json"
version.ref = "kotlinxSerialization"

[plugins.changelog]
id = "org.jetbrains.changelog"
version.ref = "changelog"

[plugins.intellijPlatform]
id = "org.jetbrains.intellij.platform"
version.ref = "intellijPlatform"

[plugins.kotlin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.kover]
id = "org.jetbrains.kotlinx.kover"
version.ref = "kover"

[plugins.qodana]
id = "org.jetbrains.qodana"
version.ref = "qodana"

[plugins.kotlinSerialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin"
